import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const C = {
  bg:         '#f4faf5',
  surface:    '#ffffff',
  surfaceAlt: '#f0faf3',
  border:     '#dceee2',
  p:          '#16a34a',
  pl:         '#22c55e',
  pd:         '#15803d',
  pxd:        '#064e3b',
  text:       '#0f2d1a',
  mid:        '#2d6a4f',
  soft:       '#5a8a6a',
  muted:      '#8aad96',
  lime:       '#74fa9e',
  hero1:      '#0a2318',
  hero2:      '#0d3320',
  hero3:      '#1a5c38',
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },

  // ── HERO ──────────────────────────────────────────────────
  hero: {
    minHeight: height,
    position: 'relative',
  },
  heroGrid: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  blob1: {
    position: 'absolute',
    width: width * 0.9,
    height: width * 0.9,
    borderRadius: width * 0.45,
    top: -width * 0.35,
    right: -width * 0.25,
    backgroundColor: 'rgba(34,197,94,0.12)',
  },
  blob2: {
    position: 'absolute',
    width: width * 0.65,
    height: width * 0.65,
    borderRadius: width * 0.325,
    bottom: height * 0.2,
    left: -width * 0.2,
    backgroundColor: 'rgba(116,250,158,0.07)',
  },
  blob3: {
    position: 'absolute',
    width: width * 0.5,
    height: width * 0.5,
    borderRadius: width * 0.25,
    top: '40%',
    left: '30%',
    backgroundColor: 'rgba(212,168,83,0.07)',
  },

  // ── NAVBAR ────────────────────────────────────────────────
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 56 : 40,
    paddingBottom: 12,
  },
  navLogoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  navLogoMark: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLogoText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.2,
  },
  navLogoSub: {
    fontWeight: '300',
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
  },
  navAdminBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  navAdminText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.75)',
  },

  // ── HERO CONTENT ──────────────────────────────────────────
  heroContent: {
    paddingHorizontal: 26,
    paddingTop: 20,
    paddingBottom: 60,
    justifyContent: 'center',
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(116,250,158,0.3)',
    borderRadius: 100,
    paddingVertical: 7,
    paddingHorizontal: 14,
    marginBottom: 24,
  },
  pulseDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#74fa9e',
  },
  heroBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1.2,
  },
  heroTitle: {
    fontSize: width > 380 ? 42 : 36,
    lineHeight: width > 380 ? 48 : 42,
    fontWeight: '300',
    color: '#fff',
    letterSpacing: -1,
    marginBottom: 16,
  },
  heroTitleAccent: {
    fontStyle: 'italic',
    color: '#74fa9e',
    fontWeight: '400',
  },
  heroSub: {
    fontSize: 14.5,
    color: 'rgba(255,255,255,0.6)',
    lineHeight: 22,
    marginBottom: 36,
  },
  heroButtons: { gap: 12, marginBottom: 40 },
  heroBtnPrimary: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  heroBtnGradient: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  heroBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  heroBtnGhost: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  heroBtnGhostText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.75)',
  },

  // ── STATS ─────────────────────────────────────────────────
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  statItem: { flex: 1, alignItems: 'center' },
  statNum: {
    fontSize: 22,
    fontWeight: '800',
    color: '#74fa9e',
  },
  statLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.4)',
    letterSpacing: 0.8,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },

  // ── SECTION GENÉRICA ──────────────────────────────────────
  section: {
    paddingVertical: 64,
    paddingHorizontal: 24,
    backgroundColor: C.bg,
  },
  sectionTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  sectionTagLine: {
    width: 20,
    height: 2,
    backgroundColor: C.pl,
    borderRadius: 1,
  },
  sectionTag: {
    fontSize: 10.5,
    fontWeight: '700',
    color: C.p,
    letterSpacing: 2,
  },
  sectionTitle: {
    fontSize: width > 380 ? 32 : 27,
    lineHeight: width > 380 ? 38 : 32,
    fontWeight: '300',
    color: C.text,
    letterSpacing: -0.5,
    marginBottom: 12,
  },
  sectionTitleAccent: {
    fontStyle: 'italic',
    color: C.p,
  },
  sectionSub: {
    fontSize: 14,
    color: C.soft,
    lineHeight: 21,
    marginBottom: 36,
  },

  // ── DISEASES ──────────────────────────────────────────────
  diseasesGrid: { gap: 16 },
  diseaseCard: {
    backgroundColor: C.surface,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: C.border,
    padding: 24,
    overflow: 'hidden',
  },
  diseaseAccentBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderRadius: 2,
  },
  diseaseIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  diseaseName: {
    fontSize: 18,
    fontWeight: '700',
    color: C.text,
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  diseaseLatin: {
    fontSize: 12,
    color: C.muted,
    fontStyle: 'italic',
    marginBottom: 12,
  },
  diseaseDesc: {
    fontSize: 13.5,
    color: C.soft,
    lineHeight: 20,
    marginBottom: 16,
  },
  diseaseTag: {
    alignSelf: 'flex-start',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 100,
    borderWidth: 1,
  },
  diseaseTagText: { fontSize: 11, fontWeight: '700' },

  // ── FEATURES ──────────────────────────────────────────────
  featuresSection: {
    position: 'relative',
    paddingBottom: 48,
  },
  featuresSectionPad: {
    paddingHorizontal: 24,
    paddingTop: 64,
    paddingBottom: 32,
  },
  featuresList: { paddingHorizontal: 24, gap: 12 },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  featureIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(34,197,94,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  featureTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  featureDesc: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.5)',
    lineHeight: 19,
  },

  // ── SCAN MOCK ─────────────────────────────────────────────
  scanBox: {
    alignItems: 'center',
    marginVertical: 32,
  },
  phoneShell: {
    width: 160,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: 'rgba(52,168,83,0.4)',
    padding: 12,
  },
  phoneNotch: {
    width: 60,
    height: 18,
    backgroundColor: '#000',
    borderRadius: 9,
    alignSelf: 'center',
    marginBottom: 10,
  },
  phoneScreen: {
    backgroundColor: '#071510',
    borderRadius: 16,
    aspectRatio: 9 / 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  scanBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1.5,
    backgroundColor: 'rgba(116,250,158,0.7)',
  },
  scanRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1.5,
    borderColor: 'rgba(34,197,94,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanRingInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(34,197,94,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanResult: {
    width: '100%',
    backgroundColor: 'rgba(22,163,74,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(22,163,74,0.25)',
    borderRadius: 8,
    padding: 10,
  },
  scanResultLabel: {
    fontSize: 8,
    color: 'rgba(255,255,255,0.35)',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  scanResultValue: {
    fontSize: 11,
    fontWeight: '700',
    color: '#74fa9e',
    marginTop: 2,
  },
  scanResultConf: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.4)',
  },
  phoneHomeBar: {
    width: 50,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignSelf: 'center',
    marginTop: 10,
  },

  // ── STEPS ─────────────────────────────────────────────────
  stepsColumn: {
    gap: 0,
    position: 'relative',
  },
  stepsConnector: {
    position: 'absolute',
    left: 44,
    top: 52,
    bottom: 52,
    width: 1.5,
    backgroundColor: C.border,
    zIndex: 0,
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: C.surface,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 18,
    marginBottom: 14,
    overflow: 'hidden',
    zIndex: 1,
  },
  stepNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.p,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  stepNumText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  stepTitle: { fontSize: 15, fontWeight: '700', color: C.text, marginBottom: 4 },
  stepDesc: { fontSize: 13, color: C.soft, lineHeight: 19, flex: 1 },

  // ── CTA ───────────────────────────────────────────────────
  ctaSection: {
    paddingVertical: 72,
    paddingHorizontal: 24,
    position: 'relative',
    alignItems: 'center',
  },
  ctaRing: {
    position: 'absolute',
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  ctaContent: { alignItems: 'center', width: '100%' },
  ctaTitle: {
    fontSize: width > 380 ? 34 : 28,
    fontWeight: '300',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 16,
    lineHeight: width > 380 ? 40 : 34,
  },
  ctaSub: {
    fontSize: 14.5,
    color: 'rgba(255,255,255,0.6)',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 36,
  },
  ctaBtnWhite: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    paddingVertical: 17,
    paddingHorizontal: 36,
    borderRadius: 14,
    marginBottom: 12,
    width: '100%',
    justifyContent: 'center',
  },
  ctaBtnWhiteText: { color: C.p, fontSize: 15, fontWeight: '700' },
  ctaBtnGhost: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    width: '100%',
    justifyContent: 'center',
  },
  ctaBtnGhostText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
  },

  // ── FOOTER ────────────────────────────────────────────────
  footer: {
    paddingVertical: 48,
    paddingHorizontal: 28,
    alignItems: 'center',
    position: 'relative',
  },
  footerLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  footerLogoMark: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerLogo: { fontSize: 15, fontWeight: '800', color: '#fff' },
  footerTagline: {
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.35)',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 24,
  },
  footerDivider: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
    marginBottom: 20,
  },
  footerCopy: {
    fontSize: 11.5,
    color: 'rgba(255,255,255,0.25)',
    marginBottom: 6,
    textAlign: 'center',
  },
  footerSena: {
    fontSize: 11,
    color: 'rgba(116,250,158,0.45)',
    textAlign: 'center',
  },
});