import { StyleSheet, Platform } from "react-native";

export const COLORS = {
    primary: '#16a34a',
    secondary: '#064e3b',
    bg: '#f0f9f1',
    surface: '#ffffff',
    text: '#1f2937',
    danger: '#ef4444',
    warning: '#f59e0b'
  };  

export const adminStyles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'row',
      height: Platform.OS === 'web' ? '100vh' : '100%', 
      width: '100%',
      backgroundColor: COLORS.bg,
      overflow: 'auto',
    },
    sidebar: {
      width: 260,
      backgroundColor: '#fff',
      padding: 20,
      borderRightWidth: 1,
      borderRightColor: '#e5e7eb',
      height: '100%',
    },
    contentWrapper: {
      flex: 1,
      maxHeight: Platform.OS === 'web' ? '100vh' : '100%',
      overflow: Platform.OS === 'web' ? 'auto' : undefined,
    },
    mainScroll: {
      flex: 1,
      width: '100%',
    },
    scrollPadding: {
      padding: 30,
      paddingBottom: 50,
    },
    logo: {
      fontSize: 22,
      fontWeight: '800',
      color: COLORS.primary,
      marginBottom: 40,
      textAlign: 'center'
    },
    sidebarItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 15,
      borderRadius: 12,
      marginBottom: 8
    },
    sidebarItemActive: {
      backgroundColor: COLORS.primary,
    },
    sidebarItemDanger: {
      marginTop: 20,
      borderTopWidth: 1,
      borderTopColor: '#e5e7eb',
    },
    sidebarLabel: {
      marginLeft: 15,
      fontWeight: '600',
      color: COLORS.secondary
    },
    mobileLogoutButton: {
  position: 'absolute',
  bottom: 20,
  right: 20,
  backgroundColor: COLORS.danger,
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 16,
  paddingVertical: 12,
  borderRadius: 30,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.2,
  shadowRadius: 4,
  elevation: 10,          // Aumenta la elevación (Android)
  zIndex: 1000,
    },
    mobileLogoutText: {
      color: '#fff',
      fontWeight: 'bold',
      marginLeft: 8,
    },
    hamburgerButton: {
      position: 'absolute',
      top: 16,
      left: 16,
      zIndex: 100,
      backgroundColor: COLORS.primary,
      padding: 10,
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    drawerOverlay: {
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.4)',
      zIndex: 200,
    },
    drawerMenu: {
      position: 'absolute',
      top: 0, left: 0, bottom: 0,
      width: 260,
      backgroundColor: '#fff',
      padding: 20,
      paddingTop: 50,
      zIndex: 300,
      shadowColor: '#000',
      shadowOffset: { width: 4, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 10,
    },
    modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'center',
  alignItems: 'center',
},
modalContainer: {
  width: '85%',
  maxWidth: 400,
  backgroundColor: '#fff',
  borderRadius: 20,
  padding: 24,
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.2,
  shadowRadius: 12,
  elevation: 8,
},
modalIcon: {
  marginBottom: 16,
},
modalTitle: {
  fontSize: 22,
  fontWeight: 'bold',
  color: '#1f2937',
  marginBottom: 12,
  textAlign: 'center',
},
modalMessage: {
  fontSize: 16,
  color: '#6b7280',
  textAlign: 'center',
  marginBottom: 24,
  lineHeight: 22,
},
modalButtons: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: '100%',
  gap: 12,
},
modalBtn: {
  flex: 1,
  paddingVertical: 12,
  borderRadius: 12,
  alignItems: 'center',
  justifyContent: 'center',
},
modalBtnCancel: {
  backgroundColor: '#e5e7eb',
},
modalBtnCancelText: {
  color: '#1f2937',
  fontWeight: '600',
  fontSize: 16,
},
modalBtnDanger: {
  backgroundColor: COLORS.danger,
},
modalBtnDangerText: {
  color: '#fff',
  fontWeight: '600',
  fontSize: 16,
},
profileHeader: {
  alignItems: 'center',
  marginBottom: 30,
  paddingBottom: 20,
  borderBottomWidth: 1,
  borderBottomColor: '#e5e7eb',
},
profileImage: {
  width: 70,
  height: 70,
  borderRadius: 35,
  marginBottom: 8,
},
profileInitials: {
  width: 70,
  height: 70,
  borderRadius: 35,
  backgroundColor: COLORS.primaryLight,
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: 8,
},
profileInitialsText: {
  fontSize: 28,
  fontWeight: 'bold',
  color: COLORS.primary,
},
profileName: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#1f2937',
  textAlign: 'center',
},
profileRole: {
  fontSize: 12,
  color: COLORS.primary,
  textAlign: 'center',
  marginTop: 4,
},
modalBtnPrimary: {
  backgroundColor: COLORS.primary,
},
modalBtnText: {
  color: '#fff',
  fontWeight: 'bold',
},
  });