import { StyleSheet } from "react-native";

export const detectionTabStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f9fafb' },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingHorizontal: 20, paddingTop: 20 },
    title: { fontSize: 24, fontWeight: '800', color: '#1f2937' },
    sub: { color: '#6b7280', fontSize: 14 },
    datasetStatsCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 12, alignItems: 'center', gap: 20, borderWidth: 1, borderColor: '#e5e7eb' },
    datasetNumber: { fontSize: 24, fontWeight: '900', color: '#16a34a' },
    datasetSub: { fontSize: 10, fontWeight: '700', color: '#9ca3af', textTransform: 'uppercase' },
    downloadBtn: { backgroundColor: '#16a34a', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
    downloadText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  
    filterContainer: { backgroundColor: '#fff', marginHorizontal: 20, marginBottom: 20, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb' },
    dateFilterRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 16, flexWrap: 'wrap' },
    dateInputGroup: { flex: 1, minWidth: 150 },
    filterLabel: { fontSize: 12, fontWeight: '700', color: '#374151', marginBottom: 6 },
    dateInput: { padding: 10, borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, fontSize: 14, backgroundColor: '#fff' },
    clearBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, padding: 10, backgroundColor: '#f3f4f6', borderRadius: 8, marginBottom: 0 },
    clearBtnText: { fontSize: 13, fontWeight: '500', color: '#6b7280' },
    filterInfo: { marginTop: 12, fontSize: 12, color: '#6b7280', fontStyle: 'italic' },
  
    mainLayout: { flexDirection: 'row', gap: 20, flex: 1, paddingHorizontal: 20 },
    listSide: { flex: 1.2, backgroundColor: '#fff', borderRadius: 20, borderWidth: 1, borderColor: '#e5e7eb', overflow: 'hidden' },
    listHeader: { padding: 18, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    listTitle: { fontWeight: '800', color: '#374151' },
    sortToggle: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#f0fdf4', padding: 8, borderRadius: 8 },
    sortToggleText: { fontSize: 12, fontWeight: '700', color: '#16a34a' },
    scrollList: { flex: 1 },
    row: { flexDirection: 'row', padding: 12, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f9fafb' },
    rowActive: { backgroundColor: '#f0fdf4' },
    miniThumb: { width: 55, height: 55, borderRadius: 10, backgroundColor: '#f3f4f6' },
    rowMainInfo: { flex: 1, marginLeft: 15 },
    rowDate: { fontSize: 11, color: '#9ca3af', marginBottom: 5 },
    typeBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
    bgRoya: { backgroundColor: '#fef3c7' },
    bgMinador: { backgroundColor: '#e0f2fe' },
    typeText: { fontSize: 11, fontWeight: '800', color: '#92400e' },
    rowValueInfo: { alignItems: 'flex-end', position: 'relative' },
    confValue: { fontSize: 16, fontWeight: '800', color: '#16a34a', textAlign: 'right' },
    confSub: { fontSize: 10, color: '#9ca3af', textAlign: 'right' },
    approvedBadge: { position: 'absolute', bottom: -5, right: -5, backgroundColor: '#16a34a', borderRadius: 10, width: 18, height: 18, justifyContent: 'center', alignItems: 'center' },
  
    inspectorSide: { flex: 1, backgroundColor: '#fff', borderRadius: 24, borderWidth: 1, borderColor: '#e5e7eb', overflow: 'hidden' },
    inspectorContent: { paddingBottom: 20 },
    mainImageWrapper: { width: '100%', height: 320, position: 'relative' },
    fullImage: { width: '100%', height: '100%', resizeMode: 'cover' },
    iaTag: { position: 'absolute', top: 15, left: 15, backgroundColor: 'rgba(22, 163, 74, 0.85)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
    iaTagText: { color: '#fff', fontSize: 11, fontWeight: '800' },
    approvedOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
    approvedOverlayText: { color: '#fff', fontWeight: 'bold', marginTop: 8 },
    mapCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f9fafb', margin: 20, padding: 15, borderRadius: 16, gap: 15, borderWidth: 1, borderColor: '#f3f4f6' },
    mapIconCircle: { width: 45, height: 45, borderRadius: 22, backgroundColor: '#fee2e2', justifyContent: 'center', alignItems: 'center' },
    mapLabel: { fontSize: 11, fontWeight: '700', color: '#9ca3af', marginBottom: 3 },
    mapValue: { fontWeight: '800', color: '#1f2937', fontSize: 14 },
    dataGrid: { flexDirection: 'row', paddingHorizontal: 20, gap: 15 },
    dataItem: { flex: 1, backgroundColor: '#f9fafb', padding: 15, borderRadius: 16 },
    dataLabel: { fontSize: 11, fontWeight: '700', color: '#9ca3af', marginBottom: 5 },
    dataValue: { fontSize: 18, fontWeight: '900', color: '#1f2937' },
    actionRow: { flexDirection: 'row', padding: 20, gap: 12 },
    approveAction: { flex: 1, backgroundColor: '#16a34a', padding: 18, borderRadius: 16, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10 },
    approveActionText: { color: '#fff', fontWeight: '800', fontSize: 16 },
    approvedActive: { backgroundColor: '#f59e0b' },
    discardAction: { width: 60, height: 60, borderRadius: 16, borderWidth: 1, borderColor: '#fecaca', justifyContent: 'center', alignItems: 'center' },
    emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
    emptyStateText: { textAlign: 'center', color: '#9ca3af', marginTop: 15, fontSize: 15, fontWeight: '600' },
    emptyList: { padding: 40, alignItems: 'center' },
    emptyListText: { color: '#9ca3af', textAlign: 'center' },
    centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
    loadingText: { marginTop: 12, color: '#6b7280' },
    errorText: { marginTop: 12, color: '#ef4444', textAlign: 'center' },
    retryBtn: { marginTop: 20, backgroundColor: '#16a34a', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8 },
    retryText: { color: '#fff', fontWeight: '700' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
    modalCard: { backgroundColor: '#fff', borderRadius: 24, padding: 30, width: '90%', maxWidth: 400, alignItems: 'center' },
    modalTitle: { fontSize: 20, fontWeight: '800', marginTop: 16, marginBottom: 8, color: '#1f2937' },
    modalMessage: { fontSize: 14, color: '#6b7280', textAlign: 'center', marginBottom: 20 },
    progressBarBg: { width: '100%', height: 10, backgroundColor: '#e5e7eb', borderRadius: 5, overflow: 'hidden', marginVertical: 16 },
    progressBarFill: { height: '100%', backgroundColor: '#16a34a', borderRadius: 5 },
    progressText: { fontSize: 13, color: '#374151', fontWeight: '500' },
    percentText: { fontSize: 16, fontWeight: '700', color: '#16a34a', marginTop: 8, textAlign: 'center' },
    completedContainer: { alignItems: 'center', marginTop: 10 },
    completedText: { fontSize: 14, color: '#16a34a', fontWeight: '600', marginTop: 16 },
    closeModalBtn: { marginTop: 20, backgroundColor: '#f3f4f6', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8 },
    closeModalText: { color: '#374151', fontWeight: '600' },
    paginationContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderTopWidth: 1,
      borderTopColor: '#e5e7eb',
      backgroundColor: '#fff',
    },
    pageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: '#f0fdf4',
    },
    pageButtonDisabled: {
      backgroundColor: '#f3f4f6',
      opacity: 0.6,
    },
    pageButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: '#16a34a',
    },
    pageButtonTextDisabled: {
      color: '#9ca3af',
    },
    pageIndicator: {
      fontSize: 13,
      fontWeight: '500',
      color: '#374151',
    },
  });
  