import { StyleSheet, Platform } from "react-native";
import {Colors} from "../../../../constants/colors"


export const usersTabStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f9fafb', padding: 20 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, flexWrap: 'wrap', gap: 10 },
    title: { fontSize: 24, fontWeight: '800', color: '#1f2937' },
    subtitle: { fontSize: 13, color: '#6b7280', marginTop: 2 },
    headerActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: '#d1fae5', backgroundColor: '#f0fdf4' },
    actionBtnText: { fontSize: 13, fontWeight: '600', color: '#16a34a' },
    refreshBtn: { padding: 10, borderRadius: 10, borderWidth: 1, borderColor: '#d1fae5', backgroundColor: '#f0fdf4' },
    growthCard: { backgroundColor: '#fff', borderRadius: 16, padding: 16, marginBottom: 20, borderWidth: 1, borderColor: '#e5e7eb' },
    growthTitle: { fontSize: 14, fontWeight: '700', marginBottom: 12, textAlign: 'center' },
    chartContainer: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', height: 150, flexWrap: 'wrap' },
    barItem: { alignItems: 'center', width: 50, marginVertical: 5 },
    barLabel: { fontSize: 10, marginBottom: 6 },
    barBg: { width: 30, height: 100, backgroundColor: '#f3f4f6', borderRadius: 4, overflow: 'hidden', justifyContent: 'flex-end' },
    barFill: { width: '100%', backgroundColor: '#16a34a', borderRadius: 4 },
    barValue: { fontSize: 10, marginTop: 4, color: '#6b7280' },
    filterTabs: { flexDirection: 'row', gap: 20, marginBottom: 16, flexWrap: 'wrap' },
    filterGroup: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
    filterGroupLabel: { fontSize: 12, fontWeight: '700', color: '#6b7280', marginRight: 4 },
    filterTab: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb' },
    filterTabActive: { backgroundColor: '#16a34a', borderColor: '#16a34a' },
    filterTabText: { fontSize: 12, fontWeight: '600', color: '#6b7280' },
    filterTabTextActive: { color: '#fff' },
    searchBar: { flexDirection: 'row', backgroundColor: '#fff', padding: 12, borderRadius: 12, alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: '#e5e7eb', gap: 8 },
    searchInput: { flex: 1, fontSize: 14, color: '#1f2937' },
    tableCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#f3f4f6', overflowX: 'auto', marginBottom: 24 },
    tableHeader: { flexDirection: 'row', padding: 14, backgroundColor: '#f9fafb', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    hText: { fontSize: 11, fontWeight: '700', color: '#9ca3af', letterSpacing: 0.5 },
    colUser: { flex: 2, minWidth: 180 },
    colRole: { flex: 1, alignItems: 'center', justifyContent: 'center', minWidth: 100, position: 'relative' },
    colStatus: { flex: 1, alignItems: 'center', justifyContent: 'center', minWidth: 80 },
    colActions: { flex: 1.5, flexDirection: 'row', justifyContent: 'flex-end', gap: 6, minWidth: 140 },
    row: { flexDirection: 'row', padding: 14, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f9fafb', flexWrap: 'wrap' },
    avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#dcfce7', justifyContent: 'center', alignItems: 'center' },
    avatarBanned: { backgroundColor: '#fee2e2' },
    avatarText: { fontWeight: '800', color: '#16a34a', fontSize: 15 },
    uName: { fontWeight: '700', color: '#1f2937', fontSize: 14 },
    textMuted: { color: '#9ca3af' },
    uEmail: { fontSize: 12, color: '#6b7280' },
    roleBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, backgroundColor: '#f3f4f6', flexDirection: 'row', alignItems: 'center', gap: 4 },
    roleText: { fontSize: 11, fontWeight: '700', color: '#6b7280' },
    statusDot: { width: 10, height: 10, borderRadius: 5 },
    dotActive: { backgroundColor: '#16a34a' },
    dotBanned: { backgroundColor: '#ef4444' },
    iconBtn: { padding: 8, borderRadius: 8, backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#f3f4f6' },
    iconBtnRed: { backgroundColor: '#fff5f5', borderColor: '#fecaca' },
    iconBtnOrange: { backgroundColor: '#fffbeb', borderColor: '#fde68a' },
    iconBtnGreen: { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' },
    centerBox: { padding: 40, alignItems: 'center', gap: 12 },
    loadingText: { color: '#6b7280', fontSize: 14 },
    errorText: { color: '#ef4444', fontSize: 14, textAlign: 'center' },
    retryBtn: { backgroundColor: '#16a34a', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8 },
    retryText: { color: '#fff', fontWeight: '700' },
    emptyBox: { padding: 40, alignItems: 'center', gap: 10 },
    emptyText: { color: '#9ca3af', fontSize: 14, textAlign: 'center' },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 20 },
    backText: { color: '#16a34a', fontWeight: '600' },
    detailHeaderCard: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: '#fff', padding: 20, borderRadius: 16, marginBottom: 20, borderWidth: 1, borderColor: '#e5e7eb' },
    detailAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#dcfce7', justifyContent: 'center', alignItems: 'center' },
    detailAvatarText: { fontWeight: '800', color: '#16a34a', fontSize: 22 },
    detailTitle: { fontSize: 20, fontWeight: '800', color: '#111827' },
    detailEmail: { fontSize: 13, color: '#6b7280', marginTop: 2 },
    detailRole: { fontSize: 12, color: '#16a34a', marginTop: 4 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 30 },
    modalCard: { backgroundColor: '#fff', borderRadius: 20, padding: 32, width: '100%', maxWidth: 420, alignItems: 'center', gap: 12 },
    modalTitle: { fontSize: 20, fontWeight: '800', color: '#111827', textAlign: 'center' },
    modalBody: { fontSize: 14, color: '#6b7280', textAlign: 'center', lineHeight: 20 },
    modalActions: { flexDirection: 'row', gap: 12, marginTop: 8, width: '100%' },
    cancelBtn: { flex: 1, padding: 14, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', backgroundColor: Colors.danger },
    cancelText: { fontWeight: '700', color: Colors.surface },
    confirmBtn: { flex: 1, padding: 14, borderRadius: 10, alignItems: 'center' },
    confirmBtnRed: { backgroundColor: '#ef4444' },
    confirmBtnOrange: { backgroundColor: '#f59e0b' },
    confirmText: { fontWeight: '700', color: '#fff' },
    paginationContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderTopWidth: 1,
      borderTopColor: '#e5e7eb',
      backgroundColor: '#fff',
      flexWrap: 'wrap',
    },
    pageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: '#f0fdf4',
    },
    pageButtonDisabled: {
      backgroundColor: '#f3f4f6',
      opacity: 0.6,
    },
    pageButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: '#16a34a',
    },
    pageButtonTextDisabled: {
      color: '#9ca3af',
    },
    pageIndicator: {
      fontSize: 13,
      fontWeight: '500',
      color: '#374151',
    },
    roleMenuLocal: {
      position: 'absolute',
      top: '100%',
      left: 0,
      backgroundColor: '#fff',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#e5e7eb',
      zIndex: 1000,
      minWidth: 100,
      marginTop: 4,
      ...Platform.select({
        web: { boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' },
        default: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 5 }
      })
    },
    roleModalCard: {
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 24,
      width: '90%',
      maxWidth: 320,
      ...Platform.select({
        web: { boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)' },
        default: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 4, elevation: 5 }
      })
    },
    roleModalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1f2937',
      textAlign: 'center',
      marginBottom: 20,
    },
    roleModalOption: {
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f3f4f6',
    },
    roleModalOptionText: {
      fontSize: 16,
      color: '#374151',
      textAlign: 'center',
      fontWeight: '500',
    },
    roleModalCancel: {
      marginTop: 16,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: Colors.danger,
    },
    roleModalCancelText: {
      fontSize: 16,
      color: Colors.surface,
      textAlign: 'center',
      fontWeight: '600',
    },
    messageModalCard: {
      backgroundColor: '#fff',
      borderRadius: 20,
      padding: 32,
      width: '90%',
      maxWidth: 380,
      alignItems: 'center',
      gap: 16,
    },
    errorModalCard: {
      borderWidth: 1,
      borderColor: '#fee2e2',
    },
    messageModalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: '#1f2937',
    },
    messageModalBody: {
      fontSize: 14,
      color: '#6b7280',
      textAlign: 'center',
      lineHeight: 20,
    },
    messageModalButton: {
      backgroundColor: '#16a34a',
      paddingHorizontal: 32,
      paddingVertical: 12,
      borderRadius: 30,
      marginTop: 8,
    },
    messageModalButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 15,
    },
    emailModalCard: {
      backgroundColor: '#fff',
      borderRadius: 20,
      padding: 24,
      width: '90%',
      maxWidth: 450,
      gap: 16,
    },
    textArea: { minHeight: 100, textAlignVertical: 'top' },
    input: {
      width: '100%',
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.primary,
      borderRadius: 8,
      padding: 12,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: '#fff',
      padding: 20,
      marginTop: 50,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    messageCard: {
      backgroundColor: '#f8fafc',
      padding: 12,
      borderRadius: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#e2e8f0',
    },
    messageDate: {
      fontSize: 12,
      color: '#64748b',
      marginBottom: 4,
    },
    messageText: {
      fontSize: 15,
      color: '#1e293b',
    },
    deleteMsgBtn: {
      alignSelf: 'flex-end',
      marginTop: 8,
    },
    noMessages: {
      textAlign: 'center',
      marginTop: 40,
      fontSize: 16,
      color: '#94a3b8',
    },
  });
  